main_timer_rate: 30.0 # [Hz]
no_cone_timeout: 60.0 # [s]

kalman_2D:

  A: [1, 0,
      0, 1]

  B: []

  # process noise
  q: 0.3
  Q: [10.0, 0,
      0, 10.0]

  # measurement covariance
  r: 1.0
  R: [1.0, 0,
      0, 100000000]

  # measurement mapping
  H: [1, 0,
      0, 1]

  initial_covariance: [10000.0, 0.0,
                       0.0, 10000.0]

kalman_3D:

  max_projection_error: !degrees 45
  n_projection_error: 5

  initial_states: [0, 0, 0.0]

  initial_covariance: [100000.0, 0.0, 0.0,
                       0.0, 100000.0, 0.0,
                       0.0, 0.0, 100000.0]

  A: [1, 0, 0,
      0, 1, 0,
      0, 0, 1]

  B: []

  # process noise
  q: 0.4
  Q: [10.0, 0, 0,
      0, 10.0, 0,
      0, 0, 10.0]

  # measurement covariance
  r: 1.0
  R: [10.0, 0, 0,
      0, 100000000, 0,
      0, 0, 100000000]

  # measurement mapping
  H: [1, 0, 0,
      0, 1, 0,
      0, 0, 1]
