cone_num: 5
constraint_offset: 0.0 # does not work (and does not make sense)

cone_mutual_min_dist:
  enabled: true
  distance: 2.0

fix_z:
  enabled: false
  z: 0.0 # [m]

fixed_camera:
  enabled: false
  distance: 0.75 # [m]

min_dist: # min distance of a solution to each cone center
  enabled: true
  distance: 2.0 # [m]

exclude_origin:
  enabled: false
  distance: 1.0 # [m]
